### ISSUE TITLE
Ausnahme PInvokeStackImbalance beim Start einer Transaction

### ISSUE THREAD

**Issue by Sentences** [fiskaly/fiskaly-kassensichv-client-dotnet#10]
Moin!
## Bug Report

Ich bekomme unter VB.NET 4.6.2 beim Client.PutAsync folgende Fehlermeldung:

> Assistent für verwaltetes Debuggen "PInvokeStackImbalance" 
>   Nachricht = Assistent für verwaltetes Debuggen "PInvokeStackImbalance" : "Ein Aufruf an die PInvoke-Funktion "FiskalyClient!Fiskaly.Client.Sma::Invoke_32" hat das Gleichgewicht des Stapels gestört. Wahrscheinlich stimmt die verwaltete PInvoke-Signatur nicht mit der nicht verwalteten Zielsignatur überein. Überprüfen Sie, ob die Aufrufkonvention und die Parameter der PInvoke-Signatur mit der nicht verwalteten Zielsignatur übereinstimmen."
> 

Die URL generiere ich so
> Dim url = "tss/" & Tss_id & "/tx/" & Guid.NewGuid.ToString & "?last_revision=0"

Beispielhaftes JSON welches gesendet werden soll:

> {
>   "state": "ACTIVE",
>   "client_id": "56f2119b-72cb-4bc2-982d-123694d8fab0",
>   "metadata": {
>     "systemuser": "Prof. Dr. Fritz Ferdinand"
>   }
> }

TSS wählen, Client wählen/anlegen funktioniert problemlos. Beim diesem Zugriff scheint aber auch versucht zu werden lokal zu verschlüsseln.
Hat irgendjemand eine Idee?

Danke

**Comment by skbg31** [comment]
Hi, füg mal in der SMA.cs beim DllImport der 32Bit Variante eine CallingConvention hinzu.


    internal static class Sma
    {
        [DllImport("com.fiskaly.kassensichv.sma-windows-386.dll", EntryPoint = "Invoke", CallingConvention = CallingConvention.Cdecl)]
        internal static extern IntPtr Invoke_32([In] byte[] request);

        [DllImport("com.fiskaly.kassensichv.sma-windows-386.dll", EntryPoint = "Free", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void Free_32(IntPtr response);

**Comment by Sentences** [comment]
Moin,
danke für die Antwort skbg31, aber das hat leider nicht geholfen. Der Fehler ist der gleiche.

**Comment by cschondorff** [comment]
Moin,
versuch einmal von AnyCPU auf x86 umzustellen. Hatte den gleichen Fehler und nach Umstellung von AnyCPU und hinzufügen der CallingConvention Anweisung hat alles besten geklappt.

**Comment by Sentences** [comment]
@cschondorff, du hast mir den Tag gerettet! Was red ich, den ganzen Monat, Danke.
Allerdings musste ich nicht mein Projekt umstellen, das stand auf x86, sondern den FiskalyClient.
