### ISSUE TITLE
Failed Schema Validation

### ISSUE THREAD

**Issue by jenshorch** [fiskaly/fiskaly-kassensichv-client-dotnet#11]
Ich bekomme immer wieder folgenden Fehler beim Schließen einer Transaktion:
`{"code":"E_FAILED_SCHEMA_VALIDATION","message":"body.log should match format \"byte\"","status_code":400,"error":"Bad Request"}`

Folgende URL versuche ich aufzurufen: https://kassensichv.fiskaly.com/api/v0/tss/145873cb-38d1-4029-9ba0-435dfcd24e4c/tx/7a02177a-1516-4a31-8e59-0e4feaa7aa5c?last_revision=1

Schaue ich mir im Debugger das Response-Objekt an stelle ich fest, dass die Request-URI plötzlich auf https://kassensichv.fiskaly.com/api/v0/tss/145873cb-38d1-4029-9ba0-435dfcd24e4c/tx/7a02177a-1516-4a31-8e59-0e4feaa7aa5c **/log** ?last_revision=1 verweist. Das scheint im TransactionHandler in der Methode OverwriteTxUrl zu passieren. Der Grund dafür ist mir unklar.

Sende ich den exakt gleichen Request (also ohne /log) manuell über Postman erhalte ich wie erwartet einen 200 und die Transaktion ist geschlossen.

Kann hier jemand erklären was da passiert und wie die Situation zu handhaben ist.

Das Verhalten scheint random aufzutreten. Bisher kann ich kein Muster erkennen. Tritt nach einiger Zeit auf.

**Comment by jenshorch** [comment]
Das Verhalten ist in der Tat eigenartig. Im Falle des 400 schicke ich den Request sofort noch ein zweites Mal weg und bekomme diesen unmittelbar mit 200 bestätigt.

**Comment by auxdevelopment** [comment]
Project moved to: https://github.com/fiskaly/fiskaly-sdk-dotnet
