### ISSUE TITLE
Zugriff per VB.NET

### ISSUE THREAD

**Issue by Olli73** [fiskaly/fiskaly-kassensichv-client-dotnet#4]
Beim Zugriff auf die ClientFactory.Create per VB.Net bekomme ich eine Fehlermeldung, da VB.Net keine "ValueTask" kennt. Nach Änderung des Rückgabetyps innerhalb der Klasse ClientFactory in einen "Task" bekomme ich nun die FehlerMeldung, dass der Webclient keinen geschützer  SSL/TLS Kanall aufgebaut werden kann.  
Gibt es eine Möglichkeit, irgendwie auf das SDK per VB.Net zuzugreifen?

**Comment by kaineder** [comment]
Ich konnte diese Probleme leider nicht reproduzieren. Folgendes minimales Beispiel wurde dafür genutzt, welches lauffähig ist:

```vb
Imports System
Imports Fiskaly.Client
Imports System.Net.Http
Imports Serilog

Module Program
    Sub Main(args As String())
        Log.Logger = New LoggerConfiguration().WriteTo.Console().CreateLogger()
        Dim apiKey as String = Environment.GetEnvironmentVariable("API_KEY")
        Dim apiSecret as String  = Environment.GetEnvironmentVariable("API_SECRET")
        Dim client As HttpClient = ClientFactory.Create(apiKey, apiSecret).AsTask().Result
    End Sub
End Module
```

```vbproj
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FiskalyClient\FiskalyClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="2.8.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>FiskalyClientVbDemo</RootNamespace>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

</Project>
```

Können Sie ein minimales Beispiel bereitstellen, welches das beschriebene Verhalten zeigt?

**Comment by Olli73** [comment]
Hallo Herr Kaineder,

den einzigen Unterschied, den ich sehe, ist, dass ich auf die 
FiskalyClient.dll im Order Bin/Debug referenziere, während Ihr Beispiel auf 
die Projectdatei referenziert.
Diesen Verweis bekomme ich so allerdings nicht hin. Ich bekomme hier die 
Fehlermeldung:
"Es konnte kein Verweis auf 
...repos\fiskaly-client-dotnet\FiskalyClient\FiskalyClient.csproj 
hinzugefügt werden. Stellen Sie sicher, dass auf die Datei zugegriffen 
werden kann und dass sie eine gültige Assembly oder COM Komponente ist"




------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: Christoph Kaineder
Betreff: Re: [fiskaly/fiskaly-kassensichv-client-dotnet] Zugriff per VB.NET 
(#4)
Datum: 21.10.2019, 7:41 Uhr
An: fiskaly/fiskaly-kassensichv-client-dotnet
Cc: Olli73, Author



Ich konnte diese Probleme leider nicht reproduzieren. Folgendes minimales 
Beispiel wurde dafür genutzt, welches lauffähig ist:

Imports System

Imports Fiskaly.Client

Imports System.Net.Http

Imports Serilog



Module Program

    Sub Main(args As String())

        Log.Logger = New LoggerConfiguration().WriteTo.Console().CreateLogger()

        Dim apiKey as String = Environment.GetEnvironmentVariable("API_KEY")

        Dim apiSecret as String  = Environment.GetEnvironmentVariable("API_SECRET")

        Dim client As HttpClient = ClientFactory.Create(apiKey, apiSecret).AsTask().Result

    End Sub

End Module

<Project Sdk="Microsoft.NET.Sdk">



  <ItemGroup>

    <ProjectReference Include="..\FiskalyClient\FiskalyClient.csproj" />

  </ItemGroup>



  <ItemGroup>

    <PackageReference Include="Serilog" Version="2.8.0" />

    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />

  </ItemGroup>



  <PropertyGroup>

    <OutputType>Exe</OutputType>

    <RootNamespace>FiskalyClientVbDemo</RootNamespace>

    <TargetFramework>netcoreapp3.0</TargetFramework>

  </PropertyGroup>



</Project>

Können Sie ein minimales Beispiel bereitstellen, welches das beschriebene 
Verhalten zeigt?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fiskaly/fiskaly-kassensichv-client-dotnet/issues/4?email_source=notifications&email_token=ANP2O5VGXGIHMCOEIHC2D33QPU6IRA5CNFSM4JCD5VD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBZDWGI#issuecomment-544357145> 
, or unsubscribe

**Comment by kaineder** [comment]
Für das Beispiel gibt es nun auch einen Pull Request (https://github.com/fiskaly/fiskaly-kassensichv-client-dotnet/pull/5).

Bitte geben Sie Bescheid, ob Ihnen das weitergeholfen hat.
