### ISSUE TITLE
Timeout/Polly Verhalten

### ISSUE THREAD

**Issue by f1oid** [fiskaly/fiskaly-kassensichv-client-dotnet#8]
Für die Zukunft ist laut ihrer readme ein Offline-Handling vorgesehen. Inwiefern wird dies die aktuelle Implementierung beeinflussen? Aktuell ist der Timeout des HttpClient auf unendlich eingestellt, was nach meinem Verständnis zu einem unendlichen Wiederholen der Polly Polilcy führt und erst durch ein Ende der maximalen Threadlaufzeit abgebrochen wird.
Da gerade der Offline Fall genau dokumentiert sein muss, sollte nicht nach einer bestimmten Zeit ein Abbruch erfolgen? Weitere Versuche sind wenig hilfreich und stehen einem Abschluss einer Transaction im Weg, da keine Sicherheit über den Zustand der erstellten Transaction besteht.
Vielen Dank im Voraus

**Comment by kaineder** [comment]
Wie Sie richtig angemerkt haben, ist für die Zukunft ein "Offline-Handling" vorgesehen. Ist die Erstellung einer signierten Lognachricht nicht möglich, muss dies dokumentiert werden und auch am Beleg ersichtlich sein (siehe https://www.bundesfinanzministerium.de/Content/DE/Downloads/BMF_Schreiben/Weitere_Steuerthemen/Abgabenordnung/AO-Anwendungserlass/2019-06-17-einfuehrung-paragraf-146a-AO-anwendungserlass-zu-paragraf-146a-AO.pdf?__blob=publicationFile&v=1). Der Polly Retry Handler wird demnach in Zukunft nicht mehr unendlich versuchen den Aufruf zu wiederholen.
